/* automatically generated by locomoto v1.22 (Hide and Seek) - http://www.eac.ea.com/tools/locale/ */

/* Language ID's */
#define IDL_ENGLISH                              0
#define IDL_GERMAN                               1
#define IDL_FRENCH                               2
#define IDL_JAPANESE                             3
#define IDL_KOREAN                               4
#define IDL_CHINESE                              5

#define LOCALE_LANGUAGE_COUNT                    6


/* string ID's */
#define STRNONE                                  0
#define LANGUAGE_STRING                          1
#define LANGUAGE_NUMBER                          2
#define IDS_OK                                   3
#define IDS_CANCEL                               4
#define IDS_VIDEO_TAB                            5
#define IDS_SOUND_TAB                            6
#define IDS_PERFORMANCE_TAB                      7
#define IDS_WWCONFIG_TITLE                       8
#define IDS_DRIVER                               9
#define IDS_VOLUME                               10
#define IDS_SOUND_EFFECTS                        11
#define IDS_MUSIC                                12
#define IDS_QUALITY                              13
#define IDS_PLAYBACK_RATE                        14
#define IDS_STEREO                               15
#define IDS_DIALOG                               16
#define IDS_DISPLAY                              17
#define IDS_COLOR_DEPTH                          18
#define IDS_LESS                                 19
#define IDS_MORE                                 20
#define IDS_WINDOWED_MODE                        21
#define IDS_DETAIL                               22
#define IDS_LOW_DESC                             23
#define IDS_HIGH_DESC                            24
#define IDS_EXPERT_MODE                          25
#define IDS_EXPERT_SETTINGS                      26
#define IDS_GEOMETRY_DETAIL                      27
#define IDS_LOW                                  28
#define IDS_HIGH                                 29
#define IDS_CHARACTER_SHADOWS                    30
#define IDS_TEXTURE_DETAIL                       31
#define IDS_PARTICLE_DETAIL                      32
#define IDS_SURFACE_EFFECT_DETAIL                33
#define IDS_LIGHTING_MODE                        34
#define IDS_TERRAIN_SHADOWS                      35
#define IDS_AUTOCONFIG                           36
#define IDS_TEXTURE_FILTER                       37
#define IDS_VERTEX                               38
#define IDS_MULTI_PASS                           39
#define IDS_MULTI_TEXTURE                        40
#define IDS_BILINEAR                             41
#define IDS_TRILINEAR                            42
#define IDS_ANISOTROPIC                          43
#define IDS_GOOD_DRIVER                          44
#define IDS_KNOW_PROBLEMS                        45
#define IDS_DRIVER_NAME                          46
#define IDS_DRIVER_VERSION                       47
#define IDS_VERSION_MIN1                         48
#define IDS_VERSION_MIN2                         49
#define IDS_NO_DRIVER_SUPPORT                    50
#define IDS_WARNING                              51
#define IDS_DO_NOT_SHOW_MSG_AGAIN                52
#define IDS_CINEMATIC                            53
#define IDS_SPEAKER_SETUP                        54
#define IDS_2_SPEAKER                            55
#define IDS_HEADPHONE                            56
#define IDS_SURROUND_SOUND                       57
#define IDS_4_SPEAKER                            58
#define IDS_8_BIT                                59
#define IDS_16_BIT                               60
#define IDS_32_BIT                               61
#define IDS_11_KHZ                               62
#define IDS_22_KHZ                               63
#define IDS_44_KHZ                               64
#define IDS_RESOLUTION                           65
#define IDS_BIT                                  66

#define LOCALE_STRING_COUNT                      67

