#pragma once

#define MESSAGEBOX_SEVERITY_MASK		0x03
#define MESSAGEBOX_BUTTONS_MASK			0x04

#define MESSAGEBOX_SEVERITY_INFO		0x00
#define MESSAGEBOX_SEVERITY_WARNING		0x01
#define MESSAGEBOX_SEVERITY_ERROR		0x02

#define MESSAGEBOX_BUTTONS_OK			0x00
#define MESSAGEBOX_BUTTONS_ABORTRETRYIGNORE	0x04

#define MESSAGEBOX_FOREGROUND			0x08

#define MESSAGEBOX_BUTTON_OK 0
#define MESSAGEBOX_BUTTON_CANCEL 1
#define MESSAGEBOX_BUTTON_ABORT 2
#define MESSAGEBOX_BUTTON_RETRY 3
#define MESSAGEBOX_BUTTON_IGNORE 4

extern int Show_Message_Box(unsigned int flags, const char *message, const char *title);
