name: openw3d-linux

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job:
    name: ${{ matrix.name }} Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 38
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu24-gcc
            os: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - name: 'CMake (configure)'
      run: |
        cmake -S . -B build ${{ matrix.cmake-args }}
    - name: 'CMake (build)'
      run: |
        cmake --build build --parallel ${{ matrix.build-args }} --target scripts

